# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',       url: 'about'}
- {name: 'Projects',    url: 'projects'}
- {name: 'Papers',      url: 'papers'}
- {name: 'CV',          url: 'cv'}
- {name: 'Contact',     url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: "google-scholar", link:   'https://scholar.google.com/citations?hl=en&user=dBrsOCMAAAAJ\'}
- {icon: "github",         link:   'https://github.com/heikestein'}
- {icon: 'twitter',        link:   'https://twitter.com/heikecstein'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
